events {}

http {
  client_max_body_size 0;

  server {
    listen 5432;

    # Route to Label Studio for all requests to root
    location / {
      proxy_pass http://label-studio:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Route to Label Studio's frontend assets
    location /label-studio-frontend/ {
      proxy_pass http://label-studio:8080/label-studio-frontend/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Route to images server for all requests starting with /images
    location /images/ {
      proxy_pass http://images_bucket:8081/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
