# Use an appropriate base image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code into the container
COPY . .

# Command to run the server
CMD ["python3", "server.py"]
